### ISSUE TITLE
Rerolled dice still count towards success total, but should not

### ISSUE THREAD

**Issue by ragibson** [ZakStrassberg/exalted-roller#4]
I don't think rerolls are meant to count towards successes (if one of the reroll values is above the target number, for instance).

For example,
`.roll/re123456789 10`
returned
![image](https://user-images.githubusercontent.com/14023456/124204062-30081c00-daac-11eb-8461-5f2090430736.png)

**Comment by Everspace** [comment]
Rerolls (reroll 10s which appear fairly commonly in charmsets) are still counted.

**Comment by ragibson** [comment]
Got it. I wasn't sure about this behavior, so I just wanted to double check.
